# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-22 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpages', '0035_auto_20180815_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='comment_requirements',
            field=models.CharField(choices=[('none', 'No comments'), ('optional', 'Optional comments'), ('required', 'Required comments')], default='none', help_text='What is the comments policy for this petition?', max_length=8),
        ),
    ]
